version = 0.1
[default.deploy.parameters]
stack_name = "new-app"
resolve_s3 = true
s3_prefix = "new-app"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "SlackURL=\"https://hooks.slack.com/services/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\""
image_repositories = []
profile = "default"
confirm_changeset = true
