AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample Slack Template

Parameters:
  SlackURL:
    Type: String
    Description: Incoming Webhook unique URL

Resources:
  SlackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/main/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 90
      Environment:
        Variables:
          SLACK_URL: !Ref SlackURL
      # Eventbridge event
      Layers:
        - !Ref Libs
      Events:
        SlackEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.config
              detail-type:
                - Config Rules Compliance Change
              detail:
                newEvaluationResult:
                  complianceType:
                    - NON_COMPLIANT
  
  Libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: slack-layer
      Description: Lambda layer with slack library
      ContentUri: ./libs
      CompatibleRuntimes:
        - python3.9
    
