AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: CloudFormation template for EventBridge rule 'SlackConfigRule'

Parameters:
  SlackAuthToken:
    Type: String
    Description: Token from slack. Example> Bearer xoxb-.......
    NoEcho: true
    MinLength: '1'
    MaxLength: '512'

Resources:
  SlackConnection:
    Type: AWS::Events::Connection
    Properties:
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: Authorization
          ApiKeyValue:
            Ref: SlackAuthToken
      Name: Slack-sam-auth
 
  SlackDestination:
    Type: AWS::Events::ApiDestination
    Properties:
      ConnectionArn:
        Fn::GetAtt:
          - SlackConnection
          - Arn
      HttpMethod: POST
      InvocationEndpoint: https://slack.com/api/chat.postMessage
      InvocationRateLimitPerSecond: 10
      Name: Slack
  
  SlackPermission:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: SlackPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:InvokeApiDestination
                Resource:
                  - !GetAtt SlackDestination.Arn

  EventRule0:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source:
          - aws.securityhub
        detail-type:
          - Security Hub Findings - Imported
        detail:
          findings:
            ProductName:
              - Config
            Severity:
              Label:
                - MEDIUM
                - CRITICAL
                - HIGH
            Workflow:
              Status:
                - NEW
      Name: Slack-Config-rule
      State: ENABLED
      Targets:
        - Id: Slack
          Arn:
            Fn::GetAtt:
              - SlackDestination
              - Arn
          RoleArn: !GetAtt SlackPermission.Arn
          InputTransformer:
            InputPathsMap:
              account: $.detail.findings[0].AwsAccountId
              description: $.detail.findings[0].Description
              region: $.detail.findings[0].Region
              resource_id: $.detail.findings[0].Resources[0].Id
              resource_type: $.detail.findings[0].Resources[0].Type
              rule_name: $.detail.findings[0].Title
              severity: $.detail.findings[0].Severity.Label
              title: $.detail.findings[0].Title
            InputTemplate: |
              {
                 "channel":"general",
                 "blocks":[
                    {
                       "type":"section",
                       "text":{
                          "type":"mrkdwn",
                          "text":"*<title>*"
                       }
                    },
                    {
                       "type":"section",
                       "text":{
                          "type":"mrkdwn",
                          "text":"• *Product Name:* AWS Config \n • *Description:* <description> \n • *Account:* <account> \n • *Region:* <region> \n • *Severity:* <severity> \n • *Resource Type:* <resource_type> \n • *Resource Id:* <resource_id> \n • *Rule Name:* _<rule_name>_"
                       },
                       "accessory":{
                          "type":"image",
                          "image_url":"https://awsvideocatalog.com/images/aws/png/PNG Light/Management & Governance/AWS-Config.png",
                          "alt_text":"config icon"
                       }
                    },
                    {
                       "type":"section",
                       "text":{
                          "type":"mrkdwn",
                          "text":">Link to rule:"
                       },
                       "accessory":{
                          "type":"button",
                          "text":{
                             "type":"plain_text",
                             "text":"Config rule",
                             "emoji":true
                          },
                          "value":"click_me_123",
                          "url":"https://<region>.console.aws.amazon.com/config/home?region=<region>#/rules/details?configRuleName=<rule_name>"
                       }
                    },
                    {
                       "type":"divider"
                    }
                 ]
              }
