AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM CLI Nested Stack for Auto Dependency Layer Creation
Metadata:
  SamCliInfo: 1.94.0
  key: AWS SAM CLI sync command
Outputs:
  MyFunctionbf3066d1DepLayer:
    Value:
      Ref: MyFunctionbf3066d1DepLayer
Resources:
  MyFunctionbf3066d1DepLayer:
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      CompatibleRuntimes:
      - python3.9
      ContentUri: /home/lep511/agit/AWS/SAM/sqs-idempotent/.aws-sam/auto-dependency-layer/MyFunctionbf3066d1DepLayer
      Description: Auto created layer for dependencies of function MyFunction
      LayerName: sam-app7427b055-MyFunctionbf3066d1-DepLayer
      RetentionPolicy: Delete
    Type: AWS::Serverless::LayerVersion
Transform: AWS::Serverless-2016-10-31
