Resources:
  numpylambdalayer11B31B47:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: pu-base-buckets-v1-provision-lab
        S3Key: 698f2c2b-6a4f-4095-b5df-7445d6b61fea/numpy_lambda_layer.zip
      CompatibleRuntimes:
        - python3.9
        - python3.8
        - python3.7
      LayerName: numpy_layer
  pandaslambdalayerC5DA5DBA:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: pu-base-buckets-v1-provision-lab
        S3Key: 698f2c2b-6a4f-4095-b5df-7445d6b61fea/pandas_lambda_layer.zip
      CompatibleRuntimes:
        - python3.9
        - python3.8
        - python3.7
      LayerName: pandas_layer
  fakerlambdalayerE1D4FA91:
    Type: AWS::Lambda::LayerVersion
    Properties:
      Content:
        S3Bucket: pu-base-buckets-v1-provision-lab
        S3Key: 698f2c2b-6a4f-4095-b5df-7445d6b61fea/faker_lambda_layer.zip
      CompatibleRuntimes:
        - python3.9
        - python3.8
        - python3.7
      LayerName: faker_layer
  LabFunctionRole82673BCB:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  LabFunctionRoleDefaultPolicyD568DC80:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:Get*
              - s3:List*
              - s3:Put*
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: LabFunctionRoleDefaultPolicyD568DC80
      Roles:
        - Ref: LabFunctionRole82673BCB
  datageneratorE992264D:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pu-base-buckets-v1-provision-lab
        S3Key: 698f2c2b-6a4f-4095-b5df-7445d6b61fea/data_generator_function.zip
      Role:
        Fn::GetAtt:
          - LabFunctionRole82673BCB
          - Arn
      Environment:
        Variables:
          input_bucket: REPLACE_WITH_INPUT_BUCKET
      FunctionName: labFunction-Data-Generator
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: fakerlambdalayerE1D4FA91
        - Ref: numpylambdalayer11B31B47
        - Ref: pandaslambdalayerC5DA5DBA
      Runtime: python3.9
      Timeout: 60
    DependsOn:
      - LabFunctionRoleDefaultPolicyD568DC80
      - LabFunctionRole82673BCB
  dataprocessor2C1D106C:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pu-base-buckets-v1-provision-lab
        S3Key: 698f2c2b-6a4f-4095-b5df-7445d6b61fea/data_processor_function.zip
      Role:
        Fn::GetAtt:
          - LabFunctionRole82673BCB
          - Arn
      Environment:
        Variables:
          input_bucket: REPLACE_WITH_INPUT_BUCKET
          output_bucket: REPLACE_WITH_OUTPUT_BUCKET
      FunctionName: labFunction-Data-Processor
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: numpylambdalayer11B31B47
        - Ref: pandaslambdalayerC5DA5DBA
      Runtime: python3.9
      Timeout: 60
    DependsOn:
      - LabFunctionRoleDefaultPolicyD568DC80
      - LabFunctionRole82673BCB
  promotionappA35F6958:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pu-base-buckets-v1-provision-lab
        S3Key: 698f2c2b-6a4f-4095-b5df-7445d6b61fea/promotion_app_function.zip
      Role:
        Fn::GetAtt:
          - LabFunctionRole82673BCB
          - Arn
      Environment:
        Variables:
          input_bucket: REPLACE_WITH_INPUT_BUCKET
          output_bucket: REPLACE_WITH_OUTPUT_BUCKET
      FunctionName: labFunction-Promotion-App
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: numpylambdalayer11B31B47
        - Ref: pandaslambdalayerC5DA5DBA
      Runtime: python3.9
      Timeout: 60
    DependsOn:
      - LabFunctionRoleDefaultPolicyD568DC80
      - LabFunctionRole82673BCB
  diyprocessor1857FAD1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pu-base-buckets-v1-provision-lab
        S3Key: 698f2c2b-6a4f-4095-b5df-7445d6b61fea/diy_processor_function.zip
      Role:
        Fn::GetAtt:
          - LabFunctionRole82673BCB
          - Arn
      Environment:
        Variables:
          input_bucket: REPLACE_WITH_INPUT_BUCKET
          output_bucket: REPLACE_WITH_OUTPUT_BUCKET
      FunctionName: labFunction-DIY-Processor
      Handler: lambda_function.lambda_handler
      Layers:
        - Ref: numpylambdalayer11B31B47
        - Ref: pandaslambdalayerC5DA5DBA
      Runtime: python3.9
      Timeout: 60
    DependsOn:
      - LabFunctionRoleDefaultPolicyD568DC80
      - LabFunctionRole82673BCB
  ec2resourcemonitoring45006DA7:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      RoleName: ec2_monitoring-role
      Tags:
        - Key: abuse-prevention
          Value: abuse-prevention
  ec2resourcemonitoringDefaultPolicyB88A5132:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ec2:Delete*
              - ec2:Describe*
              - ec2:Disable*
              - ec2:Get*
              - ec2:Revoke*
              - ec2:Stop*
              - ec2:Terminate*
              - iam:PassRole
            Effect: Allow
            Resource: "*"
        Version: "2012-10-17"
      PolicyName: ec2resourcemonitoringDefaultPolicyB88A5132
      Roles:
        - Ref: ec2resourcemonitoring45006DA7
  ec2monitoringfunctionC066F4C3:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: pu-base-buckets-v1-provision-lab
        S3Key: support/ec2_monitoring_lambda.zip
      Role:
        Fn::GetAtt:
          - ec2resourcemonitoring45006DA7
          - Arn
      Environment:
        Variables:
          maxInstance: "2"
          fraudTimeout: "60"
      FunctionName: ec2_monitoring_function
      Handler: index.lambda_handler
      MemorySize: 512
      Runtime: python3.8
      Timeout: 300
    DependsOn:
      - ec2resourcemonitoringDefaultPolicyB88A5132
      - ec2resourcemonitoring45006DA7
  ec2change:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Instance State-change Notification
        detail:
          state:
            - pending
            - running
      Targets:
        - Arn:
            Fn::GetAtt:
              - ec2monitoringfunctionC066F4C3
              - Arn
          Id: ec2_monitoring_function
  callFromEventMonitoring:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: ec2monitoringfunctionC066F4C3
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - ec2change
          - Arn