version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-nex-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-luurxx5mqoae"
s3_prefix = "sam-nex-app"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Stage=\"test\" TokenValue=\"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\""
image_repositories = []
confirm_changeset = true
