AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HugginfaceApp is a serverless application that uses AWS Lambda and Amazon API Gateway to provide a RESTful API for the HuggingFace Transformers library.

Parameters:
  Stage:
    Type: String
    Description: The stage name used in the resource names
    Default: dev
    AllowedValues:
      - test
      - dev
      - prod
    ConstraintDescription: Must be a valid stage name (test, dev, prod)
  
  
Resources:
  HuggingFaceApp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/main/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Timeout: 90
      Environment:
        Variables:
          STAGE: !Ref Stage
          API_URL: https://api-inference.huggingface.co/models/facebook/bart-large-mnli
          SECRET_NAME: !Ref SecretToken
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: post
            RestApiId: !Ref HuggingFaceAppApi
      Policies:
        SecretsManagerRead:
          - !Ref SecretToken
  Libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requests-layer
      Description: Lambda layer with requests library
      ContentUri: ./libs
      
  SecretToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: huggingface/apikey
      Description: Secret for HuggingFaceApp
      GenerateSecretString:
        SecretStringTemplate: '{"value": "TOKEN-VALUE"}'
        GenerateStringKey: value