AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HugginfaceApp is a serverless application that uses AWS Lambda and Amazon API Gateway to provide a RESTful API for the HuggingFace Transformers library.

Parameters:
  Stage:
    Type: String
    Description: The stage name used in the resource names
    Default: dev
    AllowedValues:
      - test
      - dev
      - prod
    ConstraintDescription: Must be a valid stage name (test, dev, prod)
  TokenValue:
    Type: String
    Description: The token used to authenticate with the HuggingFace API

Resources:
  HuggingFaceFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub HuggingFaceFunctionRole-${Stage}
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: !Sub HuggingFaceFunctionPolicy-${Stage}
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:huggingface/apikey*
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                Resource: '*'
  HuggingFaceApp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/main/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      MemorySize: 128
      Role: !GetAtt HuggingFaceFunctionRole.Arn
      Timeout: 90
      Environment:
        Variables:
          STAGE: !Ref Stage
          API_URL: https://api-inference.huggingface.co/models/facebook/bart-large-mnli
          SECRET_NAME: !Ref SecretToken
      Events:
        Api:
          Type: Api
          Properties:
            Path: /bartlarge
            Method: post
      Layers:
        - !Ref Libs
  
  Libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: requests-layer
      Description: Lambda layer with requests library
      ContentUri: ./libs
      CompatibleRuntimes:
        - python3.9
      
  SecretToken:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: huggingface/apikey
      Description: Secret for HuggingFaceApp
      SecretString: !Join ['', ['{"value": "', !Ref TokenValue, '"}']]
      Tags:
        - Key: Project
          Value: HuggingFaceApp
        - Key: Stage
          Value: !Ref Stage