AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  xgboost-inference-docker-lambda

  SAM Template for xgboost-inference-docker-lambda

Resources:
  XGBoostInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 256
      Timeout: 60
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  XGBoostInferenceFunction:
    Description: "XGBoostInference Lambda Function ARN"
    Value: !GetAtt XGBoostInferenceFunction.Arn
  XGBoostInferenceFunctionIamRole:
    Description: "Implicit IAM Role created for XGBoostInference function"
    Value: !GetAtt XGBoostInferenceFunction.Arn
