version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p92x617j5tlv"
s3_prefix = "sam-app"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketNamePrefix=\"sam-data\""
image_repositories = []
resolve_s3 = true
confirm_changeset = true
