version = 0.1
[default.deploy.parameters]
stack_name = "new-app-test"
resolve_s3 = true
s3_prefix = "new-app-test"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MyApiWithPathURL=\"https://api.zippopotam.us/us/*\""
image_repositories = []
