version = 0.1
[default.deploy.parameters]
stack_name = "sqs-app-new"
resolve_s3 = true
s3_prefix = "sqs-app-new"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MyApiWithPathURL=\"https://api.zippopotam.us/us/*\""
image_repositories = []
