# zexi 0.4.0
config-service_PutConfigRule:
  title: Put an &CC; rule using an &AWS; SDK
  title_abbrev: Put a rule
  synopsis: put an &CC; rule.
  category:
  languages:
    Python:
      versions:
        - sdk_version: 3
          github: python/example_code/config
          sdkguide:
          excerpts:
            - description:
              snippet_tags:
                - python.example_code.config-service.ConfigWrapper
                - python.example_code.config-service.PutConfigRule
  services:
    config-service: {PutConfigRule}
config-service_DescribeConfigRules:
  title: Describe &CC; rules using an &AWS; SDK
  title_abbrev: Describe rules
  synopsis: describe &CC; rules.
  category:
  languages:
    Python:
      versions:
        - sdk_version: 3
          github: python/example_code/config
          sdkguide:
          excerpts:
            - description:
              snippet_tags:
                - python.example_code.config-service.ConfigWrapper
                - python.example_code.config-service.DescribeConfigRules
  services:
    config-service: {DescribeConfigRules}
config-service_DeleteConfigRule:
  title: Delete an &CC; rule using an &AWS; SDK
  title_abbrev: Delete a rule
  synopsis: delete an &CC; rule.
  category:
  languages:
    Python:
      versions:
        - sdk_version: 3
          github: python/example_code/config
          sdkguide:
          excerpts:
            - description:
              snippet_tags:
                - python.example_code.config-service.ConfigWrapper
                - python.example_code.config-service.DeleteConfigRule
  services:
    config-service: {DeleteConfigRule}
