version = 0.1
[default.deploy.parameters]
stack_name = "sam-app3"
resolve_s3 = true
s3_prefix = "sam-app3"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "PowertoolsLayer=\"arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:58\""
image_repositories = []
