version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "me-otra-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zkdg62d0uikj"
s3_prefix = "me-otra-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = "BucketName=\"data-45-323-55\" Env=\"dev\""
image_repositories = []
disable_rollback = true
