version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kinesis-data-generator"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dl9soy3h8h0d"
s3_prefix = "kinesis-data-generator"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Username=\"estebanpbuday@yahoo.es\""
image_repositories = []
confirm_changeset = true
