AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pytorch-inference-docker-lambda

  SAM Template for pytorch-inference-docker-lambda

Resources:
  HeBERTInferenceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      MemorySize: 2048
      Timeout: 120
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: .
      Dockerfile: Dockerfile

Outputs:
  HeBERTInferenceFunction:
    Description: "HeBERTInference Lambda Function ARN"
    Value: !GetAtt HeBERTInferenceFunction.Arn
  HeBERTInferenceFunctionIamRole:
    Description: "Implicit IAM Role created for HeBERTInference function"
    Value: !GetAtt HeBERTInferenceFunctionRole.Arn
