AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >-
  Using an Amazon SQS queue as an idempotent queue to ensure that a message is processed only once.

Parameters:

