version = 0.1
[default.deploy.parameters]
stack_name = "samapp88"
resolve_s3 = true
s3_prefix = "samapp88"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
