version = 0.1
[default.deploy.parameters]
stack_name = "sam-app99"
resolve_s3 = true
s3_prefix = "sam-app99"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_IAM"
image_repositories = []
