[package]
name = "step-function-code-examples"
version = "0.1.0"
authors = ["Daniele Frasca <https://github.com/ymwjbxxq/>"]
edition = "2018"

[dependencies]
aws-config = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
aws-sdk-sfn = { git = "https://github.com/awslabs/aws-sdk-rust", branch = "next" }
tokio = { version = "1", features = ["full"] }
structopt = { version = "0.3", default-features = false }
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
