AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for EventBridge rule 'S3-Creation-object'
Resources:
  EventRule0:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: default
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        detail:
          bucket:
            name:
              - new-bucket-304-43
          object:
            size:
              - numeric:
                  - '>'
                  - 104857600
      Name: S3-Creation-object-new
      State: ENABLED
      Targets:
        - Id: LambdaFunctionUno
          Arn: arn:aws:lambda:us-east-1:298189759279:function:TestFunctionVideo
          InputTransformer:
            InputPathsMap:
              bucket: $.detail.bucket.name
              key: $.detail.object.key
              size: $.detail.object.size
            InputTemplate: |-
              {
                "bucket_name": <bucket>,
                "file_name": <key>,
                "file_size": <size>
              }
