version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-app-fimct"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bzlslo6xtzqs"
s3_prefix = "my-app-fimct"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StreamBucketName=\"my-bucket-4534-345\""
image_repositories = []
