AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Athena resources for data analytics

Parameters:
  StreamBucketName:
    Type: String
    Description: "S3 bucket name"

Resources:
  WorkGroupClickstream:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: clickstream
      Description: "Workgroup for clickstream data"
      RecursiveDeleteOption: true
      WorkGroupConfiguration:
        PublishCloudWatchMetricsEnabled: true
        ResultConfiguration:
          OutputLocation: !Sub s3://${StreamBucketName}/athena/results

  QryTest:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: "default"
      Description: "Test query"
      Name: "test_query"
      QueryString: "SELECT * FROM my_ingested_data;"